### ISSUE TITLE
Add a Restart button

### ISSUE THREAD

**Issue by sohailg** [Panquesito7/memory-game#1]
### Detailed description

To add Restart button for game.

### Context

If Restart button is not added then there would be a problem of person restarting the whole code again.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Hey! Thanks for reporting this! The button is already added. 😄

https://github.com/Panquesito7/memory-game/blob/a44e54f78bec78ed882b3b43df87cacfc59ad70c/src/MyForm.h#L618-L626

**Comment by sohailgi** [comment]
Great
